spring:
  application:
    name: douyin-service
  config:
    import: "optional:nacos:douyin-service-config.yaml"
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yaml
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        refresh:
          enabled: true
          
#download:
#  thread-count: 10
#  connect-timeout: 60
#  read-timeout: 60
#  write-timeout: 60
#  max-retries: 5
#  max-segment-cache: 2000
#  chunk-size: 16384

logging:
  level:
    root: INFO
    com.scccy.downloadvideo: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG