spring:
  application:
    name: douyin-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:8848
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yaml
        shared-configs:
          - data-id: douyin-service-config.yaml
            refresh: true
        refresh:
          enabled: true
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:douyin-service-config.yaml