server:
  port: 9000

spring:
  application:
    name: gateway-service
  config:
    import: "optional:nacos:gateway-config.yaml"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: douyin_swagger
          uri: lb://douyin-service
          predicates:
            - Path=/v3/api-docs/douyin-service/**,/webjars/**,/doc.html,/swagger-resources/**,/v3/api-docs/**
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: true
        register-enabled: true
      config:
        server-addr: ${NACOS_HOST:localhost}:8848
        file-extension: yaml
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        refresh:
          enabled: true
    loadbalancer:
      retry:
        enabled: true

# 日志配置
logging:
  config: classpath:log4j2-spring.xml
  level:
    com.scccy.downloadvideo: debug
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

# 监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  health:
    db:
      enabled: false  # 禁用数据源健康检查

# API文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: 抖音下载
        url: /v3/api-docs

main:
  web-application-type: reactive
  allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/your_database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver 