server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: douyin-service
          uri: lb://douyin-service
          predicates:
            - Path=/api/douyin/**
          filters:
            - StripPrefix=2
  main:
    web-application-type: reactive

# 日志配置
logging:
  config: classpath:log4j2-spring.xml
  level:
    com.scccy.downloadvideo: debug
    org.springframework.cloud.gateway: info
    reactor.netty.http.client: info

# 监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always 