server:
  port: 8090

spring:
  application:
    name: service
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_platform?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: asdsc88Q12
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  main:
    web-application-type: servlet  # 明确指定使用servlet模式

mybatis-plus:
  mapper-locations: 
    - classpath*:mapper/**/*.xml
  type-aliases-package: com.scccy.downloadvideo.service.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-level: debug
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    root: info
    com.scccy.downloadvideo: debug
  config: classpath:log4j2-spring.xml

## 自定义日志配置
#custom:
#  logging:
#    file:
#      info: ${logging.file.path}/info.log
#      warn: ${logging.file.path}/warn.log
#      error: ${logging.file.path}/error.log
#      debug: ${logging.file.path}/debug.log

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full 