CREATE TABLE IF NOT EXISTS user_info_web (
    sec_user_id VARCHAR(64) PRIMARY KEY,
    avatar_url VARCHAR(255),
    aweme_count INT,
    city VARCHAR(64),
    country VARCHAR(64),
    favoriting_count INT,
    follower_count INT,
    following_count INT,
    gender INT,
    ip_location VARCHAR(64),
    is_ban BOOLEAN,
    is_block BOOLEAN,
    is_blocked BOOLEAN,
    is_star BOOLEAN,
    live_status INT,
    mix_count INT,
    mplatform_followers_count INT,
    nickname VARCHAR(64),
    nickname_raw VARCHAR(64),
    room_id VARCHAR(64),
    school_name VARCHAR(64),
    short_id VARCHAR(64),
    signature TEXT,
    signature_raw TEXT,
    total_favorited INT,
    uid VARCHAR(64),
    unique_id VARCHAR(64),
    user_age INT,
    last_aweme_id VARCHAR(64)
); 